controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

static_content:
    path: /welcome
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
    defaults:
        template: 'welcome/page.html.twig'